#!/bin/bash

set -x

NAME=$1

SERVICE=`echo $HOSTNAME | sed -e 's/^\(.*\)-[^-]*-[^-]*$/\1/'`
IMAGE=getwarped/s2i-notebook-python35:latest

JUPYTERHUB_HOSTNAME=${JUPYTERHUB_HOSTNAME:-$SERVICE}
JUPYTERHUB_IMAGE_NAME=${JUPYTERHUB_IMAGE_NAME:-$IMAGE}

JUPYTERHUB_API_URL=http://$JUPYTERHUB_HOSTNAME:8080/hub/api

oc new-app $JUPYTERHUB_IMAGE_NAME --name $NAME \
    --labels service-type=jupyterhub-singleruser \
    --env JUPYTER_SERVICE_TYPE=jupyterhub-singleuser \
    --env JUPYTERHUB_API_TOKEN="$JUPYTERHUB_API_TOKEN" \
    --env JUPYTERHUB_API_URL="$JUPYTERHUB_API_URL" \
    --env JUPYTERHUB_SERVICE_PREFIX="$JUPYTERHUB_SERVICE_PREFIX" \
    --env JUPYTERHUB_SERVICE_NAME="$JUPYTERHUB_SERVICE_NAME" \
    --env JUPYTER_NOTEBOOK_PREFIX="$JUPYTER_NOTEBOOK_PREFIX" \
    --env JUPYTER_NOTEBOOK_USER="$JUPYTER_NOTEBOOK_USER" \
    --env JUPYTER_VOLUME_ROOTDIR="$JUPYTER_VOLUME_ROOTDIR" \
    --env JUPYTER_VOLUME_WORKDIR="$JUPYTER_VOLUME_WORKDIR"
