#!/bin/bash

set -x

IMAGE=jupyter-notebook:3.5

SERVICE=`echo $HOSTNAME | sed -e 's/^\(.*\)-[^-]*-[^-]*$/\1/'`
NAME=$SERVICE-$1

JUPYTERHUB_HOSTNAME=${JUPYTERHUB_HOSTNAME:-$SERVICE}
JUPYTERHUB_IMAGE_NAME=${JUPYTERHUB_IMAGE_NAME:-$IMAGE}

JUPYTERHUB_API_URL=http://$JUPYTERHUB_HOSTNAME:8080/hub/api

oc new-app --file jupyter-ephemeral.json \
    --param JUPYTERHUB_IMAGE_NAME="$JUPYTERHUB_IMAGE_NAME" \
    --param JUPYTER_NOTEBOOK_USER="$JUPYTER_NOTEBOOK_USER" \
    --param JUPYTERHUB_API_TOKEN="$JUPYTERHUB_API_TOKEN" \
    --param JUPYTERHUB_API_URL="$JUPYTERHUB_API_URL" \
    --param JUPYTERHUB_SERVICE_PREFIX="$JUPYTERHUB_SERVICE_PREFIX" \
    --param JUPYTERHUB_SERVICE_NAME="$JUPYTERHUB_SERVICE_NAME" \
    --param JUPYTER_NOTEBOOK_PREFIX="$JUPYTER_NOTEBOOK_PREFIX" \
    --param JUPYTER_VOLUME_ROOTDIR="$JUPYTER_VOLUME_ROOTDIR" \
    --param JUPYTER_VOLUME_WORKSPACE="$JUPYTER_VOLUME_WORKSPACE"
