#!/bin/bash

set -x

IMAGE=jupyter-notebook:3.5

SERVICE=$1
NAME=$2

JUPYTERHUB_HOST_NAME=${JUPYTERHUB_HOST_NAME:-$SERVICE}
JUPYTERHUB_IMAGE_NAME=${JUPYTERHUB_IMAGE_NAME:-$IMAGE}

JUPYTERHUB_API_URL=http://$JUPYTERHUB_HOST_NAME:8080/hub/api

JUPYTERHUB_BLUEPRINT=${JUPYTERHUB_BLUEPRINT:-persistent}

oc process --filename blueprints/$JUPYTERHUB_BLUEPRINT.json \
    --param JUPYTERHUB_IMAGE_NAME="$JUPYTERHUB_IMAGE_NAME" \
    --param JUPYTERHUB_APP_NAME="$JUPYTERHUB_APP_NAME" \
    --param JUPYTERHUB_HOST_NAME="$JUPYTERHUB_HOST_NAME" \
    --param JUPYTER_NOTEBOOK_USER="$JUPYTER_NOTEBOOK_USER" \
    --param JUPYTERHUB_API_TOKEN="$JUPYTERHUB_API_TOKEN" \
    --param JUPYTERHUB_API_URL="$JUPYTERHUB_API_URL" \
    --param JUPYTERHUB_SERVICE_PREFIX="$JUPYTERHUB_SERVICE_PREFIX" \
    --param JUPYTERHUB_SERVICE_NAME="$JUPYTERHUB_SERVICE_NAME" \
    --param JUPYTER_NOTEBOOK_PREFIX="$JUPYTER_NOTEBOOK_PREFIX" \
    --param JUPYTER_MEMORY_LIMIT="$JUPYTER_MEMORY_LIMIT" \
    --param JUPYTER_CPU_LIMIT="$JUPYTER_CPU_LIMIT" | \
    oc apply --filename -

while true; do
    sleep 1

    PODS=`oc get pod --selector notebook=$NAME \
      -o 'jsonpath={.items[?(@.status.phase=="Running")].metadata.name}'`

    if [ x"$PODS" = x"$NAME" ]; then
        break
    fi
done
