#!/bin/bash

set -x

set -eo pipefail

if [ -f /opt/app-root/etc/generate_container_user ]; then
    . /opt/app-root/etc/generate_container_user
fi

# Create a profile for 'notebook'. Add code for setting password for
# the notebook from an environment variable.

jupyter notebook --generate-config

cat >> ${HOME}/.jupyter/jupyter_notebook_config.py << !
import os
password = os.environ.get('JUPYTER_NOTEBOOK_PASSWORD')
if password:
    import notebook.auth
    c.NotebookApp.password = notebook.auth.passwd(password)
    del password
    del os.environ['JUPYTER_NOTEBOOK_PASSWORD']
!

# Start the Jupyter notebook instance.

exec jupyter notebook --no-browser --ip=0.0.0.0 --port=8080 "$@"
