#!/bin/bash

set -x

JUPYTERHUB_DATABASE_NAME=${JUPYTERHUB_DATABASE_NAME:-jupyterhub}

while true; do
    psql "postgresql://jupyterhub:$JUPYTERHUB_DATABASE_PASSWORD@$JUPYTERHUB_DATABASE_HOST:5432/$JUPYTERHUB_DATABASE_NAME" -q -c 'SELECT 1'
    if [ $? -eq 0 ]; then
        exit 0
    fi
    sleep 1
done
